version: '3.4'

networks:
  camping-images-ms-network:
    driver: bridge

services:
  camping-images-ms-postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kampi"
    networks:
      - camping-images-ms-network

  camping-images-ms-api:
    #image: campingrso/camping-images-ms:latest
    image: api
    depends_on:
      - "camping-images-ms-postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: "jdbc:postgresql://camping-images-ms-postgres:5432/kampi"
    networks:
      - camping-images-ms-network
